version: '3'

services:
  php:
    container_name: "pegasus-php"
    build:
      context: .
      args:
        - USER_ID=1000
        - USER=pegasus
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/pegasus
    restart: always
    networks:
      - pegasus

  web:
    container_name: "pegasus-nginx"
    image: nginx:1.24
    working_dir: /var/www/pegasus
    volumes:
      - ./:/var/www/pegasus:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    restart: always
    ports:
      - "${WEB_DOCKER_PORT}:80"
    networks:
      - pegasus

  db:
    container_name: "pegasus-db"
    platform: linux/x86-64
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ~/data/pegasus:/var/lib/mysql
    ports:
      - "${DB_DOCKER_PORT}:3306"
    networks:
      - pegasus

networks:
  pegasus:
    name: pegasus
    driver: bridge
